### ISSUE TITLE
Make distinction between duplicate and factored moduli

### ISSUE THREAD

**Issue by StanGirard** [zugzwang/batchgcd#1]
Hello,

great program. I found one "issue", if two n are identical then it says it is compromised. 
Your results.csv contains only id. But you could add a compromised or identical enum.

Il would be a good idea to add 
```C++
if R[i] == input_moduli[i] then type = identical
```

**Comment by zugzwang** [comment]
Hi Stan,

Thanks for this suggestion. The rationale is that, assuming this is a set of RSA keys, it could happen that two keys are equal but were taken from different origins. That could serve to impersonate each other in some cases, but yes, we should definitely make a second output containing the duplicates, because, while those keys weren't factorized, they do share factors and this program detects exactly that.

Or maybe filter out duplicates before running the algorithm?

This is still WIP, if you want to collaborate please let me know :+1: 

Cheers

**Comment by StanGirard** [comment]
You might receive a pull request from myself in the near future :) I'm looking forward to your improvements.

I just ran your program on 2M RSA keys and some of the results frighten me. A lot of public keys of size 2048 are identical from different websites. 

I'm cleaning my database and removing duplicates now before executing the script.

**Comment by StanGirard** [comment]
And great job on the product tree. I file per level was an incredible idea

**Comment by zugzwang** [comment]
I'm glad it's being useful to you. Will now work on multithreading.

> I just ran your program on 2M RSA keys and some of the results frighten me.

Just curious, were there any compromised keys? (I.e. not duplicates)

The objective of this is to learn and also try and make an improvement on the source code of [factorable.net](factorable.net) (I suggest you look at that as well, they already propose the GMP patch in order to cross the `2**32` bytes limit. I won't dare to do that patch again, I'll maybe include it here as is). The improvement I mention is to somehow make an hybrid solution that writes to disk some tree levels, not all of them, and then recompute them at fast parts of part (B) of the algorithm as necessary.  Also use some dynamic RAM/disk swapping and write to disk only when RAM is user over some user-defined limit. Finally, benchmark, and send the code to the authors and see what they think of it.

**Comment by StanGirard** [comment]
Well I just re launched the executable with 1M keys with a small modification:
```C++
for(int i = 0; i < int(input_moduli.size()); i++) {
        if(R[i] != 1) {
            if(R[i] == 0 || input_moduli[i] % R[i] != 0) {
                false_positives += 1;
            }
            else {
                if (R[i] != input_moduli[i]) {
                    compromised.push_back(IDs[i]);
                }
                
            }
        }
    }
```

I'll see if i have any compromised keys. 

When I ran it on 2M I got 20k compromised keys. But most of them were duplicates.

I'd feel better if we were not discussing breaking RSA keys and the results on the web :) The results could be frighting.

Good idea the multithreading. The code is amazing actually because the complexity is linear.

**Comment by zugzwang** [comment]
Of course. As the disclaimer goes, if these are production keys please consider informing the owners.

Yes, I agree, the algorithm is simple and powerful. It is due to [djb](https://cr.yp.to/djb.html).

**Comment by StanGirard** [comment]
Here are my results for 1M with 

```Bash
 -----------------------------------------------------
| Part (B) - Compute the remainders remᵢ <- Z mod Xᵢ² |
 -----------------------------------------------------
   Reading product tree level from data/product_tree/level20.gmp
   ok, read 1 ints of 2250502110 bits
   Computing partial remainders 0 of 19
   Computing partial remainders 1 of 19
   Computing partial remainders 2 of 19
   Computing partial remainders 3 of 19
   Computing partial remainders 4 of 19
   Computing partial remainders 5 of 19
   Computing partial remainders 6 of 19
   Computing partial remainders 7 of 19
   Computing partial remainders 8 of 19
   Computing partial remainders 9 of 19
   Computing partial remainders 10 of 19
   Computing partial remainders 11 of 19
   Computing partial remainders 12 of 19
   Computing partial remainders 13 of 19
   Computing partial remainders 14 of 19
   Computing partial remainders 15 of 19
   Computing partial remainders 16 of 19
   Computing partial remainders 17 of 19
   Computing partial remainders 18 of 19
   Computing partial remainders 19 of 19
End Part (B)
Time elapsed (s): 1398.13

 ------------------------------------------------------
|Part (C) - Compute final GCDs (remᵢ <- remᵢ/Xᵢ mod Xᵢ) |
 ------------------------------------------------------
Re-reading moduli (were destroyed in part B)
   Reading product tree level from data/product_tree/level0.gmp
   ok, read 1000000 ints of 4096 bits
Total time elapsed (s): 0h 27m 17s
Verifying correctness before announcing results

    -------------
   |-- Results --|
    -------------

Amount of compromised moduli: 0
False positives: 0
Writing compromised IDs to file...
Done, bye.

```

Without the duplicates

**Comment by zugzwang** [comment]
That's good news.

Would you consider running it again, including manually broken moduli and see if detected? For instance (2048 bit moduli, sorry about base64 encoding).
```
0,2048,3U2HRtDNm35HFs9TybruulviN2jTlCUSUzsEBygHt1ExUnHgoiBXv2T34wec1QFJUJTboyrFLB7Wdb33vqkwpMhVu928AyFv/hkEgXA6Tdf4z9fQd4ObHnm77qYQflwfcknbmyuamEQfk2y/nKJ5b4ZqFzJpg/ZjMNLQZGiZj0Tx9I2aSeO+qAAaA0qCUUueRUPAHMntwCpwAUp+XKOTBSCaCd2g43FFCK6bL+DEWj7hnHornkVjSDWxpJQJ0aE0IrJYRjyNHiD04zFWffdUtypf3ZsR9ts+YbCGg3Xah3bR8DGR52bS5AKG1cnVF9FDpaAwAeKGdqLvx8e6h9lhdQ==
1,2048,3aYlUpkrZoIcBqnd49eq6x0Pe09LN7+PbVp9jqNFkbG4UIc9OhPlG2MPWX4oZkx+AyVBAvFzPiS74LizWJ9KdRwxJ5GFArUTRdBfLr3jejXlaF9h65Y2DCaLYEX6IUe2NLkPfrysGgtHoHzOLAvnZT3qjIgTM1/e8hgnCgWs9fjqR6H7715OWjwTgVe/Mxxfwq3Bj+nP6BqZeSHSia+sHhTapglkv7AH1XLWHTHv42aG8AV7HpuyunX0cOv/JQ47eqct5wB6GWFKHDlOiRCgsRHXrL/OJ8R98CX4tGasISWRyo0+zFzUERE0W7/l0aHDa5TPVR7Wx2ALWk1sshPOvQ==
```
 Second pair:
```
0,2048,tc0hxEaedvlvI+NlgzqS+oNpI90S0Q63AtR9q8Vt1yuHWmDzX7FhmYSRJmo0/B908VZMLJm+z93xsmcfHRxpTAGsrwJaecG4woUuCQW6DiBOG1tcevFp5R2OFuxPp0qsECTlGzeNxsVs5UKsalVEzGXL8QJf3k32MpYqdaXKFroL6yJVFVpQ+FFxUS8SDx48WGq78j6RB6Z+NgyO4Zl9ImS26DBt4G2Hd+rrVIlZdjpJdDdG/IeA6VhYPVfgQzcBODT5jCEU1p5uSRuoyW9taGaN9dAyaEuj71FccrUCORRj8irt5Qzx2d1yg9LhfMZJWu0CvezwgL86aPyo30OSaw==
1,2048,xkhH/kKIEPMN1vD4jSusRaLHFoHwiO3AwHgj/Suvv34aAx+3xuC7ufWgKELzKQMXFri2E9dkce8v93J/bMZGv2pC1/yVGg/eF79dHYT3ecN/kx3EqNtqMu0ukyrzhurhAKYUWBlLrvPzfzqUpVWtZIq9GQtl+o/Moz6xRhrKsffoqXeqxvGhCV9sXFWAuoa+J2C962L8GFQxvyBUCnJmxZAadkfvQYZGsX2Q9G0PmcwZHBYYSpUbL1/6sOAcUf3FrcEWQo7CdDyLqKiZsaBW21tjwE/QjnTyJwBF+7JKZNJfXMQU20xBrThPzvL5sqEWO2c/0cHcUVGzqTzYolxNGQ==
```

**Comment by StanGirard** [comment]
```C++
for(int i = 0; i < int(input_moduli.size()); i++) {
        if(R[i] != 1) {
            if(R[i] == 0 || input_moduli[i] % R[i] != 0) {
                false_positives += 1;
            }
            else {
                if (R[i] != input_moduli[i]) {
                    compromised.push_back(IDs[i]);
                }
                
            }
        }
    }

```
Is not good it breaks some of the results even when the keys ara compromised

**Comment by zugzwang** [comment]
Hmm, strange. I'll finish the multithread improvements and address this (also the main subject of this issue, which is to make the distinction between compromised and duplicate).

**Comment by StanGirard** [comment]
I can send you a dump containing moduli if you'd like

**Comment by zugzwang** [comment]
That would be very useful, in order to set up a test suite. I generated thousands of keys only for this purpose, but the prime number sampling is slow.
Could you please write me to the email address indicated in my git profile?

**Comment by StanGirard** [comment]
100k certs coming your way :)

**Comment by zugzwang** [comment]
So, back to the discussion, I implemented writing duplicates to a separate file (also, multithreading and optimized csv processing). Closing the issue and thanks a lot for your help (feel free to reopen it if there's any bug).
