### ISSUE TITLE
Multiprocessing when number of ints  is less than number of threads

### ISSUE THREAD

**Issue by StanGirard** [zugzwang/batchgcd#11]
Is there any way to implement this ? 

When you get to 12 - 1 int multipled together you have a huge increase in calculation time because the one calculation is done by one thread. Is it possible to assign multiple threads to one calculation to increase the speed ?

**Comment by zugzwang** [comment]
I think it is possible to implement `a * b` in multithreading, yes. This depends on how multiplication is done, definitely possible in both Karatsuba and FFT methods. I do not know if `gmp` supports multithread mult though.

**Comment by zugzwang** [comment]
As revisiting how multiplication is done in `gmp` is out of the scope here, I'm closing the issue
