### ISSUE TITLE
ld: library not found for -lcrt0.o

### ISSUE THREAD

**Issue by StanGirard** [zugzwang/batchgcd#7]
Hello, I got this error after trying your new implementation. Apparently static linking is not supported on Mac OS. Do you have a workaround or should i change operating system ?

```Bash
g++ -Wall -std=c++17 -O4 -lboost_system -pthread -lboost_thread -g -I./gmp/patched/include/ -Dmpz_raw_64 src/batchgcd.cpp src/utils.cpp -lboost_system -pthread -lboost_thread -lgmp -static -L./gmp/patched/lib -o batchgcd
clang: warning: -O4 is equivalent to -O3 [-Wdeprecated]
clang: warning: -O4 is equivalent to -O3 [-Wdeprecated]
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [batchgcd] Error 1
```

**Comment by zugzwang** [comment]
Hmm not really, I'm in `Ubuntu 18.04`. Didn't know for the `-O4` vs. `-O3`, I'll put `-O3`, but for `-lcrt0.o`, please let me know if you fix this.

**Comment by StanGirard** [comment]
Just made a pull request with a fix for macos.

**Comment by zugzwang** [comment]
Hello, the PR is closed. Did you manage to find a fix for macOS?
